name: Semantic Version Tag and Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.local"

      - name: Bump version
        id: bump_version
        shell: bash
        run: |
          set -euo pipefail
          BUMP_TYPE="${{ github.event.inputs.bump }}"
          VERSION_FILE="VERSION"
          VERSION=$(cat "$VERSION_FILE")
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          if [ "$BUMP_TYPE" = "major" ]; then
            MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0
          elif [ "$BUMP_TYPE" = "minor" ]; then
            MINOR=$((MINOR+1)); PATCH=0
          else
            PATCH=$((PATCH+1))
          fi
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "$NEW_VERSION" > "$VERSION_FILE"
          git add "$VERSION_FILE"
          git commit -m "Bump version to v$NEW_VERSION"
          git tag "v$NEW_VERSION"
          git push origin "v$NEW_VERSION"
          git push origin HEAD
          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create Gitea release
        uses: https://github.com/akkuman/gitea-release-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}                 # PAT from your Gitea
          server_url: ${{ gitea.server_url }}                # e.g. https://gitea.example.com
          repository: ${{ gitea.repository }}                # owner/repo
          tag_name: v${{ steps.bump_version.outputs.NEW_VERSION }}
          name: "Release v${{ steps.bump_version.outputs.NEW_VERSION }}"
          body: "Automated release for v${{ steps.bump_version.outputs.NEW_VERSION }}."
